FROM ubuntu:bionic

COPY ./sdk_container.sh /
COPY ./build_wasm.sh /
COPY *.cc *.h *.js *.proto Makefile* *.a /sdk/

RUN ./sdk_container.sh

ENV PATH="${PATH}:/usr/local/go/bin:/root/go/bin" \
    TEST_TMPDIR=/tmp